### PR TITLE
Adds undo redo. 

### PR DESCRIPTION
**Pull request by ankeetmaini**

### CODE REVIEW

**Comment by Wildhoney** [comment]
Nice work @ankeetmaini!

**Comment by ankeetmaini** [comment]
Thanks so much @Wildhoney! It works very smooth as long as undo and redos are for separate polygons. But once I draw a polygon that merges with an existing, there it fumbles and because of the way merge is done (remove and then add new).

I'll think a little more about it.

Approach:
- I use two stacks one for `undo` and another for `redo`.
- Since create and remove are two distinct operations I store negative action to redo the same thing.
> like if a new polygon is created, add_polygon is pushed to undoStack and if I want to `undo` it, I call removeFor which again tries to push a separate action `remove_polygon` which I direct to redo stack as I know undo was in progress and vice-versa.


Let me know if you've any ideas on how to fix it for merged polygons. :)

**Comment by ankeetmaini** [comment]
I am also beginning to think `history.record` is a better name for `history.do`. :D

**Comment by ankeetmaini** [comment]
Closing this in favour of #140

**Pull request closed without merging**
